name: Build and Push Docker Image
on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set lowercase actor
        run: echo "github_actor=${GITHUB_ACTOR,,}" >> $GITHUB_ENV

      - name: Set image name
        run: echo "image_name=$GITHUB_REPOSITORY" | sed "s/=.*\//=$github_actor\//" >> $GITHUB_ENV

      - name: Set short sha tag
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set version tag
        run: echo "version=$(grep -v '^#' Dockerfile | head -n 1 | cut -d':' -f2 | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.github_actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.github_actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Push image
        uses: docker/build-push-action@v2.4.0
        with:
          target: build
          push: true
          tags: |
            ${{ env.image_name }}:latest
            ${{ env.image_name }}:${{ env.sha }}
            ${{ env.image_name }}:${{ env.version }}
            ghcr.io/${{ env.image_name }}:latest
            ghcr.io/${{ env.image_name }}:${{ env.sha }}
            ghcr.io/${{ env.image_name }}:${{ env.version }}
